booking/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'

  get 'home/index'
  get 'jwt/login_request'
  get 'jwt/logout_request'
  post 'jwt/acs'
  post 'jwt/logout'
  get 'jwt/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

booking/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

booking/app/models/jwt_configurable.rb
# frozen_string_literal: true

module JwtConfigurable
  delegate :service_name,
           :access_token_ttl,
           :rsa_private_dir,
           :rsa_public_dir,
           to: :jwt_config

  private :service_name,
          :access_token_ttl,
          :rsa_private_dir,
          :rsa_public_dir

  def jwt_config
    @jwt_config ||= OpenStruct.new Rails.configuration.jwt
  end
end

booking/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :validate_token

  private

  def validate_token
    result = ValidateToken.call(cookies[:token])
    return if result.success?

    # Rollbar.info "Validate JWT token error: #{result.failure}"
    Rails.logger.info "Validate JWT token error: #{result.failure}"
    flash[:alert] = t(result.failure)
    cookies.delete :was_authorized
    redirect_to jwt_index_path
  end
end

booking/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

booking/app/controllers/jwt_controller.rb
# frozen_string_literal: true

class JwtController < ApplicationController
  # skip_before_action :validate_token
  skip_before_action :verify_authenticity_token, :validate_token
  def index; end

  def login_request
    redirect_to idp_login_path
  end

  def logout_request
    redirect_to idp_logout_path
  end

  def acs
    ValidateToken.call(params[:token]).either(
      ->(token) {
        cookies[:token] = { value: params[:token], expires: expiry_time(token) }
        cookies[:was_authorized] = { value: true, expires: expiry_time(token), httponly: true }
      },
      ->(fail_msg) {
        flash[:alert] = t(fail_msg)
      }
    )
    redirect_to jwt_index_path
  end

  def logout
    ValidateToken.call(params[:token]).either(
      ->(_) {
        cookies.delete :token
        cookies.delete :was_authorized
      },
      ->(fail_msg) {
        flash[:alert] = t(fail_msg)
      }
    )
    redirect_to jwt_index_path
  end

  private

  def expiry_time(token)
    Time.zone.at(token.first['exp']) + 1.month
  end

  def idp_login_path
    "#{target_url}/login?token=#{login_token}&login_url=#{host_name}/jwt/login_request"
  end

  def idp_logout_path
    "#{target_url}/logout?token=#{logout_token}&login_url=#{host_name}/jwt/login_request"
  end

  def login_token
    GenerateToken.call(ENV.fetch('SSO_CALLBACK_URL')).value!
  end

  def logout_token
    GenerateToken.call(ENV.fetch('SSO_LOGOUT_CALLBACK_URL')).value!
  end

  def target_url
    ENV.fetch('SSO_TARGET_URL', 'http://localhost:8085/auth/sso/jwt')
  end

  def host_name
    ENV.fetch('HOST_NAME', 'http://localhost:8080')
  end
end

booking/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

booking/app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

booking/app/helpers/jwt_helper.rb
# frozen_string_literal: true

module JwtHelper
end

booking/app/views/jwt/acs.html.haml
%h1 Jwt#acs
%p Find me in app/views/jwt/acs.html.erb
= @result

booking/app/views/jwt/index.html.haml
- if cookies[:was_authorized]
  #root
- else
  .content.container-fluid.d-flex.flex-column.h-80
    .jumbotron.m-auto.text-center.col-sm-10.col-md-8.col-lg-6.col-xl-5
      %h1 Log in
      %hr/
      %p.lead Some text about this service
      .mt-4
        %hr/
      = link_to 'Log in', jwt_login_request_path, class: "btn btn-primary"

booking/app/views/jwt/logout.html.haml
%h1 Jwt#logout
%p Find me in app/views/jwt/logout.html.erb
= @result

booking/app/views/jwt/new.html.haml
%h1 Jwt#new
%p Find me in app/views/jwt/new.html.erb

booking/app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %title booking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  %body.bg-white
    = render "shared/navigation"
    .container
      - if notice
        %p.alert.alert-primary= notice
      - if alert
        %p.alert.alert-danger= alert
    = yield

booking/app/views/shared/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-5
  .container
    = link_to "Booking Service", root_path, class: "navbar-brand"
    %button.navbar-toggler{"aria-controls" => "navbarNav",
                           "aria-expanded" => "false",
                           "aria-label" => "Toggle navigation",
                           "data-target" => "#navbarNav",
                           "data-toggle" => "collapse",
                           type: "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse.justify-content-end
      %ul.navbar-nav
        %li.nav-item
          - if cookies[:was_authorized]
            = link_to 'Log out', jwt_logout_request_path, class: "nav-link"
          - else
            = link_to 'Log in', jwt_login_request_path, class: "nav-link"